import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Brand & App Header
    appName: 'Green Skill Agro',
    subTitle: 'Field Sales & Inventory Management Platform',
    warehouseName: 'Riyadh Central Distribution Center (WH-01)',
    liveServer: 'Live Server Connection',
    langName: 'العربية',
    switchLang: 'Switch to Saudi Arabic (RTL)',

    // Roles & Titles
    superadminRole: 'Role: Super Admin Console',
    adminRole: 'Role: Admin System Desk',
    managerRole: 'Role: Manager Control',
    sellerRole: 'Role: Field Seller Mobile',
    superadminTitle: 'Platform Super Admin',
    adminTitle: 'System Configuration',
    managerTitle: 'Operational Manager',
    sellerTitle: 'Field Representative',

    // Seller Navigation & Quick Actions
    posSale: 'POS Sale',
    vanStock: 'Van Stock',
    storePortfolio: 'Store Portfolio',
    cashSettlement: 'Cash Settlement',
    shiftOdometer: 'Shift & Odometer',
    dashboard: 'Dashboard',
    switchToManager: 'Manager',
    switchRole: 'Switch to Manager View',
    onboardNewStore: 'Onboard Store',
    settleCashBtn: 'Settle Cash',
    checkInOutBtn: 'Shift Check-In/Out',
    newSaleBtn: '+ POS Sale',

    // Seller Navigation Drawer Labels
    routeShiftOverview: 'Route & Shift Overview',
    recordNewSalePos: '+ Record New Sale (POS)',
    vehicleInventoryFefo: 'Vehicle Inventory & FEFO',
    myStorePortfolioNav: 'My Store Portfolio',
    cashBankDepositsNav: 'Cash & Bank Deposits',
    shiftAttendanceNav: 'Shift Attendance & Odometer',

    // Seller Dashboard Cards & Metrics
    cashInHand: 'Cash In Hand',
    cashLimitCeiling: 'Cash Limit Ceiling',
    assignedVehicle: 'Assigned Vehicle',
    monthlyTargetProgress: 'Monthly Target Progress',
    targetRevenue: 'Target Revenue',
    collectedAmount: 'Collected Amount',
    salesVolume: 'Sales Volume',
    storesOnboarded: 'Stores Onboarded',
    recentTransactions: 'Recent POS Sales & Settlements',
    assignedStorePortfolio: 'Assigned Store Portfolio',
    viewAllStores: 'View All Stores',
    viewFullStock: 'View Full Stock',
    cashBreachAlert: 'Cash Limit Exceeded - Settle Cash Required',
    checkedInStatus: 'Checked In (07:30 AM)',
    checkedOutStatus: 'Checked Out',

    // Seller POS Sale Page
    selectStore: 'Select Store',
    selectStorePlaceholder: 'Choose store account...',
    storeDetails: 'Store Details & Credit Position',
    creditLimit: 'Credit Limit',
    currentBalance: 'Current Balance',
    priceList: 'Price List',
    creditCycle: 'Credit Cycle',
    overdueWarning: 'Account Overdue / Limit Exceeded! Sale Blocked.',
    requestOverride: 'Request Manager Override',
    productCatalog: 'Live Vehicle Inventory Catalog',
    searchProducts: 'Search products by SKU, name...',
    categoryFilter: 'All Categories',
    addToCart: 'Add to Cart',
    cartSummary: 'Order Cart Summary',
    item: 'Item',
    unitPrice: 'Unit Price',
    qty: 'Qty',
    discount: 'Discount',
    discountCeiling: 'Discount Ceiling',
    ceilingBreach: 'Discount exceeds allowed ceiling!',
    subtotal: 'Subtotal',
    totalAmount: 'Total Amount',
    issueDeliveryDoc: 'Issue Delivery Document',
    clearCart: 'Clear Cart',
    completeSale: 'Complete POS Sale',

    // Seller Attendance Page
    shiftAttendance: 'Shift Attendance & Vehicle Odometer',
    attendanceSubtitle: 'Check-in and check-out capture selfie, auto-detected GPS location, and odometer reading.',
    startShiftCheckIn: 'Start Shift Check-In',
    endShiftCheckOut: 'End Shift Check-Out',
    selfiePhoto: 'Selfie Photo (Account Verification)',
    takeSelfie: 'Take Selfie',
    odometerPhoto: 'Odometer Photo',
    takePhoto: 'Take Odometer Photo',
    currentOdometer: 'Current Odometer Reading (km)',
    enterOdometer: 'Enter odometer km...',
    autoLocation: 'Auto-Detected GPS Location',
    locationCaptured: 'Riyadh Industrial Zone (GPS Verified)',
    logBreak: 'Log Shift Break',
    breakStatus: 'Break Time Excluded from Active Hours',
    distanceToday: 'Distance Travelled Today',
    activeHoursToday: 'Active Work Hours Today',
    shiftDetailsToday: 'Shift Details (Today)',
    checkInTimeLabel: 'Check-in Time',
    odometerStartLabel: 'Odometer Start',
    closingOdometerLabel: 'Closing Odometer Reading (km)',
    identitySelfieLabel: 'Identity Selfie Capture',
    gpsVerifiedLabel: 'GPS Verified',
    recordClosingOdometerBtn: 'Record Closing Odometer & End Shift',
    shiftClosedSuccess: 'Shift closed successfully!',
    assignedVehicleInfo: 'Assigned Vehicle Info',
    vehicleIdLabel: 'Vehicle ID:',
    registrationLabel: 'Registration:',
    modelLabel: 'Model:',

    // Seller Cash Settlement Page
    cashSettlementTitle: 'Cash Settlement & Handover',
    cashSubtitle: 'Cash collected in the field accumulates as cash in hand and requires manager approval to clear.',
    chooseRoute: 'Choose Settlement Route',
    bankDeposit: 'Bank Deposit',
    managerHandover: 'Manager Handover',
    depositAmount: 'Deposit / Handover Amount (SAR)',
    enterAmount: 'Enter amount in SAR...',
    depositSlipPhoto: 'Deposit Slip / Proof Photo',
    uploadProof: 'Upload Photo Proof',
    receivingManager: 'Receiving Manager',
    bankName: 'Target Bank / Account',
    submitHandover: 'Submit Settlement Request',
    handoverHistory: 'Settlement Request History',
    cashCeilingBreached: 'Cash Ceiling Limit Breached!',
    cashBreachDetails: 'Your current cash in hand exceeds the ceiling limit. Please submit a deposit to clear the warning flag.',
    submitCashClearance: 'Submit Cash Clearance Request',
    settlementRouteLabel: 'Settlement Route',
    amountDeclaredLabel: 'Amount Declared (SAR)',
    bankRefNoteLabel: 'Bank Reference / Deposit Note',
    photoProofLabel: 'Photographic Proof of Deposit Slip / Handover',
    submitForReviewBtn: 'Submit for Manager Review & Verification',
    handoverSubmittedMsg: 'Handover request submitted! Cash balance will reduce upon Manager approval.',
    recentSettlementRecords: 'Recent Settlement Records',
    noPendingSettlements: 'No active pending settlements.',

    // Seller Vehicle Stock Page
    vehicleInventoryRegister: 'Vehicle Inventory Register',
    unsoldStockSubtitle: 'Unsold stock remains on vehicle • Total Valuation',
    skuCode: 'SKU Code',
    productName: 'Product Name',
    category: 'Category',
    packSize: 'Pack Size',
    vanQty: 'Van Quantity',
    batchLot: 'Batch / LOT',
    expiryDate: 'Expiry Date',
    fefoStatus: 'FEFO Clearance Status',
    vendorLabel: 'Vendor',
    unitsLabel: 'units',
    healthyStock: 'Healthy Stock',
    expiringSoon: 'Expiring Soon',

    // Seller Store Portfolio Page
    myStorePortfolio: 'My Store Portfolio',
    assignedStoresInRoute: 'Assigned stores in route',
    searchStoresPlaceholder: 'Search store name, owner, city...',
    showingStores: 'Showing Stores',
    storeAndOwner: 'Store & Owner',
    cityCol: 'City',
    creditCycleTerms: 'Credit Cycle Terms',
    outstandingBalanceCol: 'Outstanding Balance',
    blockedPastDue: 'BLOCKED (Past Due)',
    createSaleBtn: 'Create Sale',

    // New Store Modal
    onboardNewStoreTitle: 'Onboard New Store',
    systemRuleNewStore: 'System Rule: Storefront photo and auto-detected GPS coordinates are captured. CR/VAT numbers are optional. New stores require Manager approval before first sale.',
    storeNameLabel: 'Store Name',
    storeNamePlaceholder: 'e.g. Al-Waha Agricultural Store',
    ownerNameLabel: 'Owner / Contact Person',
    ownerNamePlaceholder: 'Owner Full Name',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+966 50 XXX XXXX',
    cityRegionLabel: 'City / Region',
    crNumberLabel: 'CR Number (Optional)',
    vatNumberLabel: 'VAT Number (Optional)',
    proposedCreditCycleLabel: 'Proposed Credit Cycle',
    proposedCreditLimitLabel: 'Proposed Credit Limit (SAR)',
    storefrontEvidenceLabel: 'Storefront Photographic Evidence',
    submitStoreForApprovalBtn: 'Submit Store for Manager Approval',
    weeklyCycle: 'Weekly Cycle',
    monthlyCycle: 'Monthly Cycle (30-Day)',
    billToBill: 'Bill to Bill (Pay-on-Delivery)',

    // Manager / Executive Dashboard & Tabs
    executiveDashboard: 'Executive Dashboard',
    vehicleFleetSellers: 'Vehicle Fleet & Sellers',
    warehouseStock: 'Warehouse & Stock',
    purchaseOrdersPO: 'Purchase Orders (PO)',
    warehouseDispatches: 'Warehouse Dispatches',
    storesCreditLedger: 'Stores & Credit Ledger',
    cashHandovers: 'Cash & Handovers',
    attendanceRoutes: 'Attendance & Routes',
    reorderForecasting: 'Reorder Forecasting',
    operationalControl: 'Operational Control',

    // Admin Sidebar & Pages
    systemRulesCeilings: 'System Rules & Ceilings',
    productTemplatesCatalog: 'Product Templates & Catalog',
    vendorDirectoryPO: 'Vendor Directory & PO Approvals',
    userRolesPermissions: 'User Roles & Permissions',
    returnRulesFeatures: 'Return Rules & Feature Toggles',
    systemAuditTrail: 'System Audit & Activity Trail',
    adminConfiguration: 'Admin Configuration',

    // Super Admin Sidebar & Pages
    enterpriseOversight: 'Enterprise Oversight',
    userAdminGovernance: 'User & Admin Governance',
    masterHierarchyMatrix: 'Master Hierarchy & Matrix',
    centralWarehouseWH01: 'Central Warehouse (WH-01)',
    securityKillSwitches: 'Security & Kill-Switches',
    superAdminGovernance: 'Super Admin Governance',

    // Manager Actions & Workflows
    searchPlaceholder: 'Search SKU, PO, Store, Vendor...',
    issueVehicleLoadout: 'Issue Vehicle Loadout',
    auditVehicleStock: 'Audit Vehicle Stock',
    convertSkuRepackage: 'Convert SKU / Repackage',
    draftPurchaseOrder: 'Draft Purchase Order',
    setupProductSku: 'Setup Product / SKU',
    managerWorkflows: 'Manager Workflows',

    // Approval Queue & Metrics
    systemStockPosition: 'System Stock Position',
    warehouseHub: 'Warehouse (WH-01)',
    vehicleFleetVans: 'Vehicle Fleet (4 Vans)',
    inTransitPipeline: 'In-Transit (PO Pipeline)',
    expiryAtRisk: 'Expiry At Risk (30d)',
    collectionsCashHandover: 'Collections & Cash Handover',
    approvedDeposits: 'Approved Deposits',
    pendingReview: 'Pending Review',
    overdueBalances: 'Overdue Balances',
    todaysRevenueDispatches: 'Today\'s Revenue & Dispatches',
    fieldVanSales: 'Field Van Sales',
    directWhDispatches: 'Direct WH Dispatches',
    pendingDispatchRelease: 'Pending Dispatch Release',
    fieldWorkforceFleet: 'Field Workforce & Fleet',
    activeShiftsSelfie: 'Active Shifts (Selfie Verified)',
    cashLimitBreaches: 'Cash Limit Breaches',
    overdueVehicleAudits: 'Overdue Vehicle Audits',
    managerApprovalQueue: 'Manager Approval & Operational Action Queue',
    stockWriteOffsTab: 'Stock Write-Offs',
    dispatchesTab: 'Warehouse Dispatches',
    cashTab: 'Cash & Deposits',
    creditTab: 'Credit Overrides',
    storesTab: 'Store Onboarding',
    lossValue: 'Loss Value',
    orderValue: 'Order Value',
    declaredCash: 'Declared Cash',
    saleValue: 'Sale Value',
    processDispatch: 'Process Dispatch',
    viewSlip: 'View Slip',
    verifyHandover: 'Verify Handover',
    grantOverride: 'Grant Override',
    lockedBySuperAdmin: 'Locked by Super Admin',
    storefrontPhotoBtn: 'Storefront Photo',
    approveStoreBtn: 'Approve Store',
    switchToSeller: 'Switch to Field Seller View',

    // Table Headers & Statuses
    id: 'ID',
    name: 'Name',
    role: 'Role',
    status: 'Status',
    date: 'Date',
    action: 'Action',
    active: 'Active',
    activeHub: 'Active Central Hub',
    pending: 'Pending',
    draft: 'Draft',
    approved: 'Approved',
    inTransit: 'In Transit',
    partiallyReceived: 'Partially Received',
    fullyReceived: 'Fully Received',
    closed: 'Closed',
    maintenanceMode: 'Maintenance Mode',
    blocked: 'Blocked',
    alert: 'Alert',
    expiry: 'Expiry',
    review: 'Review',
    live: 'Live (Online)',

    // Common Buttons & Modals
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    close: 'Close',
    back: 'Back',
    edit: 'Edit',
    delete: 'Delete',
    viewDetails: 'View Details',
    approve: 'Approve',
    reject: 'Reject',
    override: 'Override',
    filter: 'Filter',
    noDataFound: 'No records found',

    // Extended Approval Queue & Actions
    viewEvidence: 'View Evidence',
    approveWriteOff: 'Approve Write-Off',
    approveStore: 'Approve Store',
    viewPhoto: 'View Photo',
    reason: 'Reason',
    submittedBy: 'Submitted By',
    holdingLocation: 'Location',
    shortfall: 'Shortfall',
    outstanding: 'Outstanding',
    declared: 'Declared',

    // System Rules & Ceilings
    systemRulesTitle: 'System-Wide Rules & Governance Ceilings',
    systemRulesDesc: 'Configure company-wide operational limits, cash ceilings, discount guardrails, and audit windows for Green Skill Agro.',
    saveSystemParams: 'Save System Parameters',
    paramsSavedSuccess: 'Configuration parameters successfully updated and active system-wide!',
    maxSellerDiscount: 'Max Seller Discount Ceiling',
    maxDiscountDesc: 'Maximum discount percentage a field seller can apply without Manager approval override.',
    permittedDiscountLabel: 'Permitted Seller Ceiling (%)',
    discountRuleNote: 'System Rule: Disciplinary alert triggered if seller exceeds this ceiling.',
    dailyCashCeiling: 'Seller Daily Cash Ceiling (SAR)',
    maxCashDesc: 'Maximum un-deposited cash balance a seller can hold before system blocks POS sales.',
    maxCashLimitLabel: 'Max Cash Limit (SAR)',
    cashLockNote: 'System Rule: Automatic POS lock active when cash exceeds ceiling.',
    storeCreditGrace: 'Store Credit Grace Period (Days)',
    creditGraceDesc: 'Days past due before store account is automatically flagged for credit lock.',
    graceDaysLabel: 'Grace Period (Days)',
    creditLockNote: 'System Rule: Auto credit block triggers after grace period expiry.',
    expiryWarningWindow: 'Inventory Expiry Warning Window (Days)',
    expiryWindowDesc: 'Days remaining before expiry date when FEFO clearance alert triggers on seller van stock.',
    warningDaysLabel: 'Warning Window (Days)',
    fefoAlertNote: 'System Rule: FEFO clearance warning badges appear in Seller Van Stock view.',

    // Super Admin & Admin Governance
    provisionAdmin: '+ Provision Admin Account',
    userDirectoryTitle: 'Platform User Directory & Role Governance',
    userDirectoryDesc: 'Manage access rights, role escalation, and account status for all Kingdom users.',
    filterRole: 'Filter Role:',
    hubScope: 'Hub/Scope:',
    searchUsersPlaceholder: 'Search user name, ID, email...',
    userId: 'User ID',
    userNameContact: 'User Name & Contact',
    roleHierarchy: 'Role Hierarchy',
    assignedHubScope: 'Assigned Hub / Scope',
    governanceActions: 'Governance Actions',
    rootAuthority: 'Root Authority',
    suspend: 'Suspend',
    activate: 'Activate',
    platformRoleHierarchy: 'Platform Role Hierarchy Architecture',
    strictDelegation: 'Enforces strict role delegation: Super Admin > Admin > Manager > Seller',
    functionalCapabilityMatrix: 'Functional Capability Matrix',
    functionalMatrixDesc: 'Detailed breakdown of system capability per role across enterprise functional domains.',
    emergencyKillSwitches: 'Platform Emergency Kill-Switches',
    emergencyKillDesc: 'Super Admin supreme override controls. Enabling a switch instantly locks target platform operations across the central warehouse and field operations.',
    engageLock: 'ENGAGE LOCK',
    releaseLock: 'RELEASE LOCK',
    activeOverrideEngaged: 'Active: Security Override Engaged',
    auditTrailTitle: 'Kingdom Executive Audit Trail',
    auditTrailDesc: 'Immutable audit log of all system configuration changes, role escalations, and security events.',
    riskTier: 'Risk Tier',

    // Profile Page
    myProfile: 'My Profile',
    profileSubtitle: 'Manage profile photo, name, phone, address, and password credentials',
    personalInfo: 'Personal Information',
    roleInfo: 'Role & Account Governance',
    grantedPermissions: 'Granted Operational Permissions',
    fullName: 'Full Name',
    corporateEmail: 'Corporate Email Address',
    phoneNumber: 'Phone Number',
    completeAddress: 'Complete Address',
    assignedRole: 'Assigned Role',
    accountStatusLabel: 'Account Status',
    readOnlyNotice: 'Read-Only Field (Managed by System Administrator)',
    editableNotice: 'User Editable Field',
    securityNoticeTitle: 'Security & Access Policy',
    securityNoticeBody: 'Profile photo, full name, phone number, address, and password are editable by you. Email, assigned role, and permissions are managed by System Administrator.',
    changePhoto: 'Upload New Photo',
    removePhoto: 'Remove Photo',
    photoSuccessToast: 'Profile photo updated successfully!',
    photoRemovedToast: 'Profile photo reset to default avatar.',
    uploadImagePreview: 'Photo Preview',
    resetPasswordSection: 'Reset Account Password',
    resetPasswordDesc: 'Update your login password credentials securely.',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    saveProfileChanges: 'Save Profile Changes',
    resetPasswordBtn: 'Reset Password',
    profileUpdatedSuccess: 'Profile details updated successfully!',
    passwordResetSuccess: 'Password reset successfully!',
    passwordMismatchError: 'New password and confirm password do not match!',
    currentPasswordRequired: 'Please enter your current password.'
  },
  ar: {
    // Brand & App Header
    appName: 'غرين سكيل أغرو',
    subTitle: 'منصة إدارة المبيعات الميدانية والمخزون',
    warehouseName: 'مركز التوزيع المركزي بالرياض (WH-01)',
    liveServer: 'اتصال حي بالسيرفر',
    langName: 'English',
    switchLang: 'Switch to English',

    // Roles & Titles
    superadminRole: 'الدور: لوحة المشرف العام',
    adminRole: 'الدور: مكتب إدارة النظام',
    managerRole: 'الدور: التحكم التشغيلي للمدير',
    sellerRole: 'الدور: تطبيق المندوب الميداني',
    superadminTitle: 'المشرف العام للمنصة',
    adminTitle: 'إعدادات وهيئة النظام',
    managerTitle: 'مدير العمليات',
    sellerTitle: 'مندوب المبيعات الميداني',

    // Seller Navigation & Quick Actions
    posSale: 'بيع نقاط البيع (POS)',
    vanStock: 'مخزون الشاحنة',
    storePortfolio: 'محفظة المتاجر',
    cashSettlement: 'تصفية النقدية',
    shiftOdometer: 'الوردية وعداد الكيلومترات',
    dashboard: 'الرئيسية',
    switchToManager: 'المدير',
    switchRole: 'التحويل إلى وضع المدير',
    onboardNewStore: 'إضافة متجر جديد',
    settleCashBtn: 'تصفية النقدية',
    checkInOutBtn: 'تسجيل الوردية (دخول/خروج)',
    newSaleBtn: '+ بيع جديد (POS)',

    // Seller Navigation Drawer Labels
    routeShiftOverview: 'نظرة عامة على المسار والوردية',
    recordNewSalePos: '+ تسجيل بيع جديد (POS)',
    vehicleInventoryFefo: 'مخزون الشاحنة والصلاحية (FEFO)',
    myStorePortfolioNav: 'محفظة المتاجر الخاصة بي',
    cashBankDepositsNav: 'النقدية والإيداعات البنكية',
    shiftAttendanceNav: 'حضور الوردية وقراءة العداد',

    // Seller Dashboard Cards & Metrics
    cashInHand: 'النقدية بحوزة المندوب',
    cashLimitCeiling: 'الحد الأقصى للنقدية المسموحة',
    assignedVehicle: 'الشاحنة المخصصة',
    monthlyTargetProgress: 'تقدم الهدف الشهرى',
    targetRevenue: 'إيراد الهدف المطلوب',
    collectedAmount: 'المبالغ المحصلة',
    salesVolume: 'حجم المبيعات',
    storesOnboarded: 'المتاجر المسجلة',
    recentTransactions: 'آخر مبيعات نقاط البيع والتسويات',
    assignedStorePortfolio: 'محفظة المتاجر المخصصة',
    viewAllStores: 'عرض جميع المتاجر',
    viewFullStock: 'عرض المخزون الكامل',
    cashBreachAlert: 'تم تجاوز حد النقدية - يلزم تصفية النقدية فوراً',
    checkedInStatus: 'تم تسجيل الدخول (07:30 صباحاً)',
    checkedOutStatus: 'تم تسجيل الخروج',

    // Seller POS Sale Page
    selectStore: 'اختيار المتجر',
    selectStorePlaceholder: 'اختر حساب المتجر...',
    storeDetails: 'تفاصيل المتجر والوضع الائتماني',
    creditLimit: 'الحد الائتماني',
    currentBalance: 'الرصيد الحالي',
    priceList: 'قائمة الأسعار',
    creditCycle: 'دورة الائتمان',
    overdueWarning: 'الحساب متأخر / تجاوز الحد! البيع محظور.',
    requestOverride: 'طلب تجاوز من المدير',
    productCatalog: 'كتالوج مخزون الشاحنة الحي',
    searchProducts: 'ابحث عن صنف بالاسم أو الكود...',
    categoryFilter: 'جميع الفئات',
    addToCart: 'إضافة للسلة',
    cartSummary: 'ملخص سلة الطلب',
    item: 'الصنف',
    unitPrice: 'سعر الوحدة',
    qty: 'الكمية',
    discount: 'الخصم',
    discountCeiling: 'سقف الخصم',
    ceilingBreach: 'الخصم يتجاوز السقف المسموح به!',
    subtotal: 'المجموع الفرعي',
    totalAmount: 'المبلغ الإجمالي',
    issueDeliveryDoc: 'إصدار سند التسليم',
    clearCart: 'تفريغ السلة',
    completeSale: 'إتمام عملية البيع',

    // Seller Attendance Page
    shiftAttendance: 'حضور الوردية وعداد الكيلومترات',
    attendanceSubtitle: 'تسجيل الدخول والخروج يلتقط صورة صورة سيلفي، موقع GPS تلقائي، وقراءة العداد.',
    startShiftCheckIn: 'تسجيل دخول الوردية',
    endShiftCheckOut: 'تسجيل خروج الوردية',
    selfiePhoto: 'صورة السيلفي (التحقق من الحساب)',
    takeSelfie: 'التقاط صورة سيلفي',
    odometerPhoto: 'صورة عداد الكيلومترات',
    takePhoto: 'التقاط صورة العداد',
    currentOdometer: 'قراءة العداد الحالية (كم)',
    enterOdometer: 'أدخل قراءة العداد بالكيلومتر...',
    autoLocation: 'موقع GPS المكتشف تلقائياً',
    locationCaptured: 'منطقة الرياض الصناعية (متحقق منه عبر GPS)',
    logBreak: 'تسجيل استراحة وردية',
    breakStatus: 'وقت الاستراحة مستثنى من ساعات العمل النشطة',
    distanceToday: 'المسافة المقطوعة اليوم',
    activeHoursToday: 'ساعات العمل النشطة اليوم',
    shiftDetailsToday: 'تفاصيل الوردية (اليوم)',
    checkInTimeLabel: 'وقت تسجيل الدخول',
    odometerStartLabel: 'عداد بداية الوردية',
    closingOdometerLabel: 'قراءة عداد إغلاق الوردية (كم)',
    identitySelfieLabel: 'صورة السيلفي للتحقق من الهوية',
    gpsVerifiedLabel: 'متحقق منه عبر GPS',
    recordClosingOdometerBtn: 'تسجيل قراءة الإغلاق وإنهاء الوردية',
    shiftClosedSuccess: 'تم إغلاق الوردية بنجاح!',
    assignedVehicleInfo: 'معلومات الشاحنة المخصصة',
    vehicleIdLabel: 'معرف الشاحنة:',
    registrationLabel: 'اللوحة:',
    modelLabel: 'الموديل:',

    // Seller Cash Settlement Page
    cashSettlementTitle: 'تصفية وتسليم النقدية',
    cashSubtitle: 'تتراكم المبالغ المحصلة في الميدان كـ "نقدية بحوزة المندوب" وتتطلب موافقة المدير لتصفيتها.',
    chooseRoute: 'اختر مسار التصفية',
    bankDeposit: 'إيداع بنكي',
    managerHandover: 'تسليم يدوي للمدير',
    depositAmount: 'مبلغ الإيداع / التسليم (ريال)',
    enterAmount: 'أدخل المبلغ بالريال السعودي...',
    depositSlipPhoto: 'صورة إيصال الإيداع / الإثبات',
    uploadProof: 'رفع صورة الإثبات',
    receivingManager: 'المدير المستلم',
    bankName: 'البنك / الحساب المستهدف',
    submitHandover: 'إرسال طلب التصفية',
    handoverHistory: 'سجل طلبات التصفية',
    cashCeilingBreached: 'تم تجاوز الحد الأقصى للنقدية!',
    cashBreachDetails: 'المبالغ النقدية بحوزتك تتجاوز السقف المسموح. يرجى تقديم طلب إيداع بنكي أو تسليم لإزالة التنبيه.',
    submitCashClearance: 'تقديم طلب تصفية النقدية',
    settlementRouteLabel: 'مسار التصفية',
    amountDeclaredLabel: 'المبلغ المعلن (ريال سعودي)',
    bankRefNoteLabel: 'الرقم المرجعي / ملاحظة الإيداع',
    photoProofLabel: 'إثبات مصور لإيصال الإيداع / التسليم',
    submitForReviewBtn: 'إرسال للمراجعة والاعتماد من المدير',
    handoverSubmittedMsg: 'تم تقديم طلب التصفية بنجاح! سيتم خصم المبلغ من رصيدك فور اعتماد المدير.',
    recentSettlementRecords: 'سجل طلبات التصفية الأخيرة',
    noPendingSettlements: 'لا توجد طلبات تصفية قيد الانتظار.',

    // Seller Vehicle Stock Page
    vehicleInventoryRegister: 'سجل مخزون الشاحنة',
    unsoldStockSubtitle: 'المخزون المتبقي بالشاحنة • التقييم الإجمالي',
    skuCode: 'رمز الصنف (SKU)',
    productName: 'اسم المنتج',
    category: 'الفئة',
    packSize: 'حجم العبوة',
    vanQty: 'كمية الشاحنة',
    batchLot: 'رقم التشغيلة / الدفعة',
    expiryDate: 'تاريخ الصلاحية',
    fefoStatus: 'حالة الصلاحية (FEFO)',
    vendorLabel: 'المورد',
    unitsLabel: 'وحدة',
    healthyStock: 'مخزون سليم',
    expiringSoon: 'قريب الانتهاء',

    // Seller Store Portfolio Page
    myStorePortfolio: 'محفظة المتاجر الخاصة بي',
    assignedStoresInRoute: 'المتاجر المخصصة في مسار',
    searchStoresPlaceholder: 'ابحث باسم المتجر، المالك، المدينة...',
    showingStores: 'عرض المتاجر',
    storeAndOwner: 'المتجر والمالك',
    cityCol: 'المدينة',
    creditCycleTerms: 'شروط دورة الائتمان',
    outstandingBalanceCol: 'الرصيد المستحق',
    blockedPastDue: 'محظور (متأخرات)',
    createSaleBtn: 'إنشاء عملية بيع',

    // New Store Modal
    onboardNewStoreTitle: 'تسجيل متجر جديد',
    systemRuleNewStore: 'قاعدة النظام: يتم التثبت من صورة واجهة المتجر وإحداثيات GPS تلقائياً. السجل التجاري والتحقق الضريبي اختياري. المتاجر الجديدة تتطلب موافقة المدير قبل أول عملية بيع.',
    storeNameLabel: 'اسم المتجر',
    storeNamePlaceholder: 'مثال: تسجيل متجر الواحة الزراعي',
    ownerNameLabel: 'المالك / الشخص المسؤول',
    ownerNamePlaceholder: 'الاسم الكامل للمالك',
    phoneLabel: 'رقم الهاتف',
    phonePlaceholder: '+966 50 XXX XXXX',
    cityRegionLabel: 'المدينة / المنطقة',
    crNumberLabel: 'رقم السجل التجاري (اختياري)',
    vatNumberLabel: 'الرقم الضريبي (اختياري)',
    proposedCreditCycleLabel: 'دورة الائتمان المقترحة',
    proposedCreditLimitLabel: 'الحد الائتماني المقترح (ريال سعودي)',
    storefrontEvidenceLabel: 'إثبات مصور لوجهة المتجر',
    submitStoreForApprovalBtn: 'إرسال المتجر لاعتماد المدير',
    weeklyCycle: 'دورة أسبوعية',
    monthlyCycle: 'دورة شهرية (30 يوم)',
    billToBill: 'فاتورة بفاتورة (الدفع عند التسليم)',

    // Manager / Executive Dashboard & Tabs
    executiveDashboard: 'لوحة التحكم التنفيذية',
    vehicleFleetSellers: 'أسطول الشاحنات والمندوبين',
    warehouseStock: 'المستودع والمخزون',
    purchaseOrdersPO: 'أوامر الشراء (PO)',
    warehouseDispatches: 'طلبات التوزيع المباشر',
    storesCreditLedger: 'المتاجر وسجل الائتمان',
    cashHandovers: 'التسويات والمبالغ النقدية',
    attendanceRoutes: 'الحضور ومسارات السير',
    reorderForecasting: 'توقعات إعادة الطلب',
    operationalControl: 'التحكم التشغيلي',

    // Admin Sidebar & Pages
    systemRulesCeilings: 'قواعد وقيود النظام',
    productTemplatesCatalog: 'قوالب المنتجات والكتالوج',
    vendorDirectoryPO: 'دليل الموردين واعتماد الشراء',
    userRolesPermissions: 'أدوار وصلاحيات المستخدمين',
    returnRulesFeatures: 'شروط الإرجاع ومفاتيح الميزات',
    systemAuditTrail: 'سجل تتبع نشاط النظام',
    adminConfiguration: 'إعدادات الأدمن',

    // Super Admin Sidebar & Pages
    enterpriseOversight: 'الرقابة العامة للمنشأة',
    userAdminGovernance: 'إدارة المستخدمين والمدراء',
    masterHierarchyMatrix: 'مصفوفة الهيكل التنفيذي',
    centralWarehouseWH01: 'المستودع المركزي (WH-01)',
    securityKillSwitches: 'أزرار الطوارئ والحماية',
    superAdminGovernance: 'إدارة المشرف العام',

    // Manager Actions & Workflows
    searchPlaceholder: 'بحث في الأصناف، أوامر الشراء، المتاجر، الموردين...',
    issueVehicleLoadout: 'صرف مخزون لشاحنة',
    auditVehicleStock: 'جرد مخزون الشاحنة',
    convertSkuRepackage: 'تحويل وتعبئة الأصناف',
    draftPurchaseOrder: 'إنشاء مسودة أمر شراء',
    setupProductSku: 'إعداد منتج / صنف جديد',
    managerWorkflows: 'إجراءات المدير التشغيلية',

    // Approval Queue & Metrics
    systemStockPosition: 'موقع مخزون النظام',
    warehouseHub: 'المستودع المركزي (WH-01)',
    vehicleFleetVans: 'أسطول الشاحنات (4 شاحنات)',
    inTransitPipeline: 'مخزون قيد الطريق (أوامر الشراء)',
    expiryAtRisk: 'مخزون قريب الانتهاء (30 يوم)',
    collectionsCashHandover: 'التحصيلات وتصفية النقدية',
    approvedDeposits: 'الإيداعات المعتمدة',
    pendingReview: 'مراجعة قيد الانتظار',
    overdueBalances: 'الأرصدة المتأخرة',
    todaysRevenueDispatches: 'إيرادات وطلبات اليوم',
    fieldVanSales: 'مبيعات الشاحنات الميدانية',
    directWhDispatches: 'طلبات التوزيع المباشرة',
    pendingDispatchRelease: 'طلبات صرف قيد الانتظار',
    fieldWorkforceFleet: 'القوى العاملة الميدانية والأسطول',
    activeShiftsSelfie: 'الورديات النشطة (متحقق منها)',
    cashLimitBreaches: 'تجاوزات حد النقدية',
    overdueVehicleAudits: 'جرد الشاحنات المتأخر',
    managerApprovalQueue: 'طابور اعتمادات المدير والإجراءات التشغيلية',
    stockWriteOffsTab: 'إسقاط المخزون',
    dispatchesTab: 'التوزيع المباشر',
    cashTab: 'النقدية والإيداعات',
    creditTab: 'تجاوزات الائتمان',
    storesTab: 'اعتماد المتاجر',
    lossValue: 'قيمة الخسارة',
    orderValue: 'قيمة الطلب',
    declaredCash: 'النقدية المعلنة',
    saleValue: 'قيمة البيع',
    processDispatch: 'معالجة الصرف',
    viewSlip: 'عرض الإيصال',
    verifyHandover: 'تأكيد التسليم',
    grantOverride: 'منح التجاوز',
    lockedBySuperAdmin: 'مقفل من المشرف العام',
    storefrontPhotoBtn: 'صورة المتجر',
    approveStoreBtn: 'اعتماد المتجر',
    switchToSeller: 'التحويل إلى وضع المندوب الميداني',

    // Table Headers & Statuses
    id: 'المعرف',
    name: 'الاسم',
    role: 'الدور',
    status: 'الحالة',
    date: 'التاريخ',
    action: 'الإجراء',
    active: 'نشط',
    activeHub: 'مستودع مركزي نشط',
    pending: 'قيد الانتظار',
    draft: 'مسودة',
    approved: 'معتمد',
    inTransit: 'في الطريق',
    partiallyReceived: 'مستلم جزئياً',
    fullyReceived: 'مستلم بالكامل',
    closed: 'مغلق',
    maintenanceMode: 'وضع الصيانة',
    blocked: 'محظور',
    alert: 'تنبيه',
    expiry: 'صلاحية',
    review: 'مراجعة',
    live: 'حي (متصل)',

    // Common Buttons & Modals
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    submit: 'إرسال',
    close: 'إغلاق',
    back: 'رجوع',
    edit: 'تعديل',
    delete: 'حذف',
    viewDetails: 'عرض التفاصيل',
    approve: 'موافقة',
    reject: 'رفض',
    override: 'تجاوز',
    filter: 'تصفية',
    noDataFound: 'لا توجد سجلات',

    // Extended Approval Queue & Actions
    viewEvidence: 'عرض الإثبات',
    approveWriteOff: 'اعتماد الإسقاط',
    approveStore: 'اعتماد المتجر',
    viewPhoto: 'عرض الصورة',
    reason: 'السبب',
    submittedBy: 'مقدم الطلب',
    holdingLocation: 'الموقع',
    shortfall: 'النقص',
    outstanding: 'المستحقات',
    declared: 'المعلن',

    // System Rules & Ceilings
    systemRulesTitle: 'قواعد وقيود النظام الشاملة',
    systemRulesDesc: 'ضبط الحدود التشغيلية وسقوف النقدية وضوابط الخصم وفترات التدقيق لـ غرين سكيل أغرو.',
    saveSystemParams: 'حفظ إعدادات النظام',
    paramsSavedSuccess: 'تم تحديث إعدادات النظام بنجاح وهي نشطة الآن على مستوى المنشأة!',
    maxSellerDiscount: 'السقف الأقصى لخصم المندوب',
    maxDiscountDesc: 'النسبة المئوية القصوى للخصم التي يمكن للمندوب تطبيقها دون موافقة المدير.',
    permittedDiscountLabel: 'سقف الخصم المسموح (%)',
    discountRuleNote: 'قاعدة النظام: يتم تفعيل تنبيه عند تجاوز المندوب لهذا السقف.',
    dailyCashCeiling: 'السقف اليومي للنقدية بحوزة المندوب (ريال)',
    maxCashDesc: 'الحد الأقصى للنقدية غير المودعة قبل أن يقوم النظام بحظر مبيعات نقاط البيع.',
    maxCashLimitLabel: 'الحد الأقصى للنقدية (ريال)',
    cashLockNote: 'قاعدة النظام: يتم قفل مبيعات POS تلقائياً عند تجاوز النقدية للسقف.',
    storeCreditGrace: 'فترة سماح ائتمان المتاجر (أيام)',
    creditGraceDesc: 'عدد الأيام بعد استحقاق الفاتورة قبل حظر حساب المتجر تلقائياً.',
    graceDaysLabel: 'فترة السماح (أيام)',
    creditLockNote: 'قاعدة النظام: يتم تطبيق حظر الائتمان تلقائياً بعد انتهاء فترة السماح.',
    expiryWarningWindow: 'نافذة التنبيه بقرب انتهاء صلاحية المخزون (أيام)',
    expiryWindowDesc: 'عدد الأيام المتبقية على انقضاء الصلاحية لتفعيل تنبيه التصريف المبكر (FEFO).',
    warningDaysLabel: 'نافذة التنبيه (أيام)',
    fefoAlertNote: 'قاعدة النظام: تظهر شارات تنبيه التصريف المبكر (FEFO) في مخزون الشاحنة.',

    // Super Admin & Admin Governance
    provisionAdmin: '+ إنشاء حساب أدمن جديد',
    userDirectoryTitle: 'دليل مستخدمي المنصة وحوكمة الصلاحيات',
    userDirectoryDesc: 'إدارة حقوق الوصول، تصعيد الصلاحيات، وحالة الحسابات لجميع مستخدمي المملكة.',
    filterRole: 'تصفية حسب الدور:',
    hubScope: 'الفرع / النطاق:',
    searchUsersPlaceholder: 'ابحث باسم المستخدم، المعرف، البريد...',
    userId: 'معرف المستخدم',
    userNameContact: 'اسم المستخدم وبيانات التواصل',
    roleHierarchy: 'تسلسل الصلاحيات',
    assignedHubScope: 'الفرع / النطاق المخصص',
    governanceActions: 'إجراءات الحوكمة',
    rootAuthority: 'السلطة العليا',
    suspend: 'تجميد',
    activate: 'تنشيط',
    platformRoleHierarchy: 'هيكلية تسلسل الصلاحيات بالأدوار',
    strictDelegation: 'تطبيق التدرج في السلطة: المشرف العام > الأدمن > المدير > المندوب',
    functionalCapabilityMatrix: 'مصفوفة الصلاحيات والإمكانيات الوظيفية',
    functionalMatrixDesc: 'تفصيل كامل للإمكانيات المتاحة لكل دور عبر القطاعات التشغيلية.',
    emergencyKillSwitches: 'أزرار الحماية والطوارئ بالنظام',
    emergencyKillDesc: 'صلاحيات الاستثناء العليا للمشرف العام. تفعيل أي زر يقفل فوراً العمليات المستهدفة عبر المستودع المركزي والميدان.',
    engageLock: 'تفعيل القفل',
    releaseLock: 'إلغاء القفل',
    activeOverrideEngaged: 'نشط: استثناء الحماية مفعّل',
    auditTrailTitle: 'سجل التتبع والمراجعة التنفيذية بالمملكة',
    auditTrailDesc: 'سجل غير قابل للتعديل لجميع تغييرات هيئة النظام وتعديلات الصلاحيات والأحداث الأمنية.',
    riskTier: 'مستوى الخطورة',

    // Profile Page
    myProfile: 'ملفي الشخصي',
    profileSubtitle: 'إدارة الصورة الشخصية، الاسم، رقم الهاتف، العنوان، وكلمة المرور',
    personalInfo: 'المعلومات الشخصية',
    roleInfo: 'حكومة الدور والحساب',
    grantedPermissions: 'الصلاحيات التشغيلية الممنوحة',
    fullName: 'الاسم الكامل',
    corporateEmail: 'البريد الإلكتروني للشركة',
    phoneNumber: 'رقم الهاتف',
    completeAddress: 'العنوان الكامل',
    assignedRole: 'الدور المعين',
    accountStatusLabel: 'حالة الحساب',
    readOnlyNotice: 'حقل للقراءة فقط (يتم إدارته بواسطة مدير النظام)',
    editableNotice: 'حقل قابل للتعديل بواسطة المستخدم',
    securityNoticeTitle: 'سياسة الأمان والصلاحيات',
    securityNoticeBody: 'يمكنك تعديل الصورة الشخصية والاسم ورقم الهاتف والعنوان وكلمة المرور. يتم إدارة البريد الإلكتروني والدور والصلاحيات بواسطة مدير النظام.',
    changePhoto: 'رفع صورة جديدة',
    removePhoto: 'إزالة الصورة',
    photoSuccessToast: 'تم تحديث الصورة الشخصية بنجاح!',
    photoRemovedToast: 'تم إعادة ضبط الصورة الشخصية إلى الافتراضية.',
    uploadImagePreview: 'معاينة الصورة',
    resetPasswordSection: 'إعادة ضبط كلمة المرور للحساب',
    resetPasswordDesc: 'تحديث بيانات تسجيل الدخول وكلمة المرور بأمان.',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    saveProfileChanges: 'حفظ تغييرات الملف الشخصي',
    resetPasswordBtn: 'إعادة ضبط كلمة المرور',
    profileUpdatedSuccess: 'تم تحديث بيانات الملف الشخصي بنجاح!',
    passwordResetSuccess: 'تم إعادة ضبط كلمة المرور بنجاح!',
    passwordMismatchError: 'كلمة المرور الجديدة وتأكيدها غير متطابقين!',
    currentPasswordRequired: 'يرجى إدخال كلمة المرور الحالية.'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('green_skill_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('green_skill_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    if (language === 'ar') {
      document.body.classList.add('rtl-mode');
    } else {
      document.body.classList.remove('rtl-mode');
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, isRtl: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
